name: paper2code
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.11
  - pip>=23.0
  - pytorch=2.1.2
  - torchvision=0.16.2
  - numpy=1.26
  - pip:
    - opencv-python>=4.8.0
    - timm==0.9.12
    - scipy>=1.11.0
    - gdown>=5.2.0
    - -e git+https://github.com/LTH14/torch-fidelity.git@master#egg=torch-fidelity
    - git+https://github.com/open-mmlab/mmcv.git@d409eedc816fccfb1c8d57e5eed5f03bd075f327
    - git+https://github.com/Lakonik/mmgeneration.git@500a93e474638c87dcaf8fad94cfbe1ef29acd1f
    - git+https://github.com/huggingface/diffusers.git@57084dacc5275d7212513b24837b60a28e55603d
    - transformers
    - torchsde
    - setuptools>=65.5.1
    - apex==0.9.10dev
    - bitsandbytes
    - yapf==0.40.1
    - ml_collections
    - hydra-core
    - pandas>=2.0.0
    - omegaconf
    - wandb
    - jax>=0.4.13
    - jaxlib>=0.4.13
    - pyarrow
    - h5py
    - flax
    - dmlab2d
    - git+https://github.com/deepmind/meltingpot.git@v2.4.0
    - einops
    - tensordict
    - torchrl
    - google-genai
    - openai