model:
    vq_model:
        quantize_mode: vae

losses:
    discriminator_start: 0
    discriminator_factor: 1.0
    discriminator_weight: 0.1
    quantizer_weight: 1.0
    perceptual_loss: "lpips"
    perceptual_weight: 1.0
    reconstruction_loss: "l1"
    reconstruction_weight: 1.0
    lecam_regularization_weight: 0.0
    kl_weight: 1e-6
    logvar_init: 0.0
